<a href="https://colab.research.google.com/github/beatricexc/Artificial-Intelligence-Machine-Learning/blob/main/Artificial_Neural_Network_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np
import matplotlib.pyplot as plt

#storing the data in a 2-dimensional array
# X = (hours sleeping, hours studying), y = Score on test 
X = np.array(([3,5], [5,1], [10,2]), dtype = float)
y = np.array(([75], [82], [93]),)
print(X)

[[ 3.  5.]
 [ 5.  1.]
 [10.  2.]]


In [28]:
print(y)

[[75]
 [82]
 [93]]


Predicting the test score based on slept hours and hours studied the night before the exam. In oder words, we will be predicting the output value *y* which are scores for a given set of input values X which are hours of (sleep, study)

In [29]:
#Scaling the data so the result is in [0,1]
X = X/np.amax(X, axis = 0)
y = y/100
X

array([[0.3, 1. ],
       [0.5, 0.2],
       [1. , 0.4]])

In [30]:
y

array([[0.75],
       [0.82],
       [0.93]])

Building the Neural Network. 

IT must have 2 inputs (X) and 1 output(y)We'll call our output 
^
y
, because it's an estimate of 
y



Any layer between the input and output layer is called  a **hidden layer** . Here we're going to use just one hidden layer with 3 neurons along with the sigmoid function.

In [31]:
 print(X.shape,y.shape)

(3, 2) (3, 1)


In [32]:
X

array([[0.3, 1. ],
       [0.5, 0.2],
       [1. , 0.4]])

In [33]:
y

array([[0.75],
       [0.82],
       [0.93]])

Building the network as a python class. The init() method of the class will take care of instantiating constants and variables.

In [36]:
class NeuralNetwork(object):
  def self():
    self.inputLayerSize = 2
    self.hiddenLayerSize = 3
    self.outputLayerSize = 1

  def forwardPropagation(self, X):
    pass

To be continued....